name: flutter_slides
description: An app for running a slide presentation.

environment:
  flutter: ">=1.10.7-pre.94"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  scoped_model: ^0.3.0
  watcher: ^0.9.7+10
  lottie_flutter: ^0.2.0
  spritewidget: ^0.9.17
  flare_flutter: ^1.5.4
  nima: ^1.0.5

  # Desktop embedder plugins.
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      ref: 403355819d784ab51af55e5de556de03618996ba
      path: plugins/file_chooser
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      ref: 403355819d784ab51af55e5de556de03618996ba
      path: plugins/menubar
#  shared_preferences_fde:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      ref: 403355819d784ab51af55e5de556de03618996ba
#      path: plugins/flutter_plugins/shared_preferences_fde

  # Flutter plugins
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/fonts/GoogleSans/
  - assets/flare/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansNoLiga/GoogleSansNoLiga-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSansNoLiga/GoogleSansNoLiga-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: RobotoMono
      fonts:
      - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        weight: 400
